### ISSUE TITLE
Cannot cancel Testrun in 'Waiting for Device' status

### ISSUE THREAD

**Issue by jboddey** [google/testrun#139]
**Describe the bug**
You cannot cancel a Testrun if it is waiting for a device because the button is not present.

**To Reproduce**
1) Start a testrun
2) Do not connect device
3) Attempt to cancel

**Expected behavior**
The cancel button should be present in this state

**Comment by Aksinnia-Dzenisenka** [comment]
Covered in scope of 303857989

**Comment by jboddey** [comment]
This has been resolved and will be released in v1.1
