### ISSUE TITLE
Report shows wrong IPv6 SLAAC source address

### ISSUE THREAD

**Issue by travellingmonk** [google/testrun#170]
The IPv6 SLAAC address displayed in the report differs from what is observed in the packet capture. This address remains consistent across all reports, indicating it may be associated with either DHCP server 1 or 2. Please refer to the accompanying screenshots, which illustrate two distinct reports featuring the same address.

![2](https://github.com/google/testrun/assets/149505525/e2069621-c09b-4605-b63a-14235e6a3b19)

![1](https://github.com/google/testrun/assets/149505525/921e698c-df0e-4a0c-bdf6-b7c6c5aa678d)

**Comment by jboddey** [comment]
This has been fixed in #131 and is now in dev. Will be released in December in full launch
