### ISSUE TITLE
No message when no appropriate network adapters are available

### ISSUE THREAD

**Issue by jboddey** [google/testrun#187]
**What is the problem your feature is trying to solve?**
When the user has no appropriate network adapters available, the connection settings dialog is empty and does not indicate whether there was an error or there are no adapters available.

**Describe the solution you think would solve the problem**
A message should be present that no suitable network adapters are available and maybe a suggestion to connect an ethernet connection.
![A83KyrHkhSwLZpv](https://github.com/google/testrun/assets/7399056/440d5828-b542-442e-8636-a8f4e95c3b6c)

Testrun version: v1.1-alpha

**Comment by KrystsinaT** [comment]
The FE ticket is 311162313
