### ISSUE TITLE
Error occurs when deleting device from repository

### ISSUE THREAD

**Issue by jboddey** [google/testrun#188]
**Describe the bug**
When attempting to delete a device from the device repository, an error code of 500 is returned.

**To Reproduce**
Open the device repository
Press delete device
Press confirm

**Expected behavior**
The device should be deleted without error and should be removed from the device repository

Testrun version: v1.1-alpha

**Comment by KrystsinaT** [comment]
FE ticket is 311162951 for bug verification.
