### ISSUE TITLE
Version number is placed incorrectly

### ISSUE THREAD

**Issue by jboddey** [google/testrun#199]
**Describe the bug**
The current Testrun version number is not padded or centered in the left navigation menu.

**Expected behavior**
The version number should be either centered or padded appropriately.

**Error logs**
![image](https://github.com/google/testrun/assets/7399056/736bbaff-8d10-4a41-8f11-4fdff0814fb5)

**Comment by KrystsinaT** [comment]
314961821 reported on the UI component

**Comment by jboddey** [comment]
This is now resolved and will be released in v1.1
