### ISSUE TITLE
SSH/ OpenSSH Versioning on Testrun Report

### ISSUE THREAD

**Issue by travellingmonk** [google/testrun#200]
In the 'security.ssh.version' test, the description includes the OpenSSH version, which could be perplexing for the end user when reviewing the report. Please refer to the attached screenshot for clarification.

![image](https://github.com/google/testrun/assets/149505525/0edba34d-b675-4e77-a423-7f50c956064e)
![image](https://github.com/google/testrun/assets/149505525/d240e194-1279-4499-b46a-8c881cbdf79d)

[nmap.log](https://github.com/google/testrun/files/13560286/nmap.log)
[container.log](https://github.com/google/testrun/files/13560287/container.log)
[nmap-result.json](https://github.com/google/testrun/files/13560293/nmap-result.json)

**Comment by jboddey** [comment]
@travellingmonk Could you run an nmap scan on this device and share the version picked up there?

**Comment by travellingmonk** [comment]
sure thing!

**Comment by jboddey** [comment]
Closing this as we are not looking to fix this.
