### ISSUE TITLE
Testrun UI info - Step 1 missing, Step 2 appears randomly

### ISSUE THREAD

**Issue by travellingmonk** [google/testrun#201]
A glitch has been identified in the header information labeled 'i,' which is currently visible at the top of the page. Step 1 does not seem to be appearing, and Step 2 is loading unpredictably. Refer to the screenshot provided below for further clarification:

![MicrosoftTeams-image](https://github.com/google/testrun/assets/149505525/fa898541-0f63-46d6-a170-730def859057)

**Comment by jboddey** [comment]
@travellingmonk Step 1 has disappeared because it has already been completed (You have created at least 1 device). If this was confusing, what do you think would be easier to understand for new users?

**Comment by travellingmonk** [comment]
@jboddey ah, but if you hit F5 (refresh), Step 1 appears for like a milli second, hence confused me.

**Comment by jboddey** [comment]
Related bug ID: 314276839

**Comment by jboddey** [comment]
This has now been resolved and will be released in v1.1
