### ISSUE TITLE
Loading animation above settings panel

### ISSUE THREAD

**Issue by jboddey** [google/testrun#206]
**Describe the bug**
The waiting for device loading animation is rendered above the settings panel. See the attached image.

![image](https://github.com/google/testrun/assets/7399056/31c0a3aa-cf59-43e8-9a22-92287b3dc854)

**Comment by KrystsinaT** [comment]
315944556

**Comment by KrystsinaT** [comment]
Fixed on the UI component.

**Comment by jboddey** [comment]
Fixed in PR #213
