### ISSUE TITLE
Ability to shutdown Testrun

### ISSUE THREAD

**Issue by jboddey** [google/testrun#210]
**What is the problem your feature is trying to solve?**
Currently, to stop Testrun completely, the user must find the open console window running Testrun and press Ctrl+C to end. It is not possible to do this through the UI.

**Describe the solution you think would solve the problem**
The user should be able to shutdown Testrun from the user interface.

**Comment by KrystsinaT** [comment]
316594878  was reported on UI component.

**Comment by jboddey** [comment]
This feature request is now in progress and is expected to be released in v1.2.1 (end of Apr/start of May).

**Comment by jboddey** [comment]
Released in v1.2.2
