### ISSUE TITLE
--single-intf  ignored ?

### ISSUE THREAD

**Issue by ptorrent** [google/testrun#259]
Seems that --single-intf  is ignored ? 

Event if I start testrun --single-intf

![image](https://github.com/google/testrun/assets/6083644/9ca278c9-e26a-473c-b7b8-9d2507c7a9b5)

**Comment by ptorrent** [comment]
Solved by changing the same button disable="false" ...

**Comment by jboddey** [comment]
Hi @ptorrent, thanks for reporting this bug. The single interface is currently ignored by the user interface but you can override these interfaces by modifying /usr/local/testrun/local/system.json with the correct device interface name. The UI will be updated end of Q1 to allow for just one interface to be selected.

**Comment by KrystsinaT** [comment]
323348124

**Comment by jboddey** [comment]
This bug has been resolved in version 1.1.2 which is due to release in the next couple of days.

**Comment by ptorrent** [comment]
thanks for the feedback !
