### ISSUE TITLE
Testrun finishes after 45 minutes complaining no NTP request

### ISSUE THREAD

**Issue by chspeck** [google/testrun#269]
**Describe the bug**
The NTP poll interval of our machine is configured around 18 hours.  The test finishes after 45 minutes.
According to earlier times when google did this testing they agreed that such a high interval time is valid and they prolonged the measurement interval for our device.

**To Reproduce**
Use a device with high ntp poll interval time. 
1. Start testrun
2. Wait until test 'fails'

**Expected behavior**
a) Test shall inform that ntp request is missing and waits until condition is fullfilled
b) provide a way to specify observation time (command line argument for testrun?)

**Error logs**
n.a.

**Environment (please provide the following information about your setup):**
 - Ubuntu]
 - Version  22.04

**Additional context**
n.a.

**Comment by jboddey** [comment]
Hi @chspeck, thank you for reporting this bug. I will discuss with the qualification team how we want to go about this. It may be something that must be demonstrated during the remote validation phase of qualification. It do not think it would be viable to have Testrun wait ~18 hours before completion.

**Comment by chspeck** [comment]
> Hi @chspeck, thank you for reporting this bug. I will discuss with the qualification team how we want to go about this. It may be something that must be demonstrated during the remote validation phase of qualification. It do not think it would be viable to have Testrun wait ~18 hours before completion.

And a command line option to specify observation time?

**Comment by jboddey** [comment]
You can modify the monitor period in /usr/local/testrun/local/system.json. However, the device should send an NTP request on boot. Are you powering on the device once Testrun has started testing rather than leaving the device powered on?

**Comment by jboddey** [comment]
@chspeck Please could you reach out to anniappan@google.com and maggiecastle@google.com with this question please?

**Comment by jboddey** [comment]
Hi @chspeck, there is no specific documentation on the system.json file as we recommend users do not generally modify this configuration. Instead, configuration should be made through the user interface. However, see below for some detail on this file:

```
{
  "network": {
    "device_intf": "enx123456789123",
    "internet_intf": "enx123456789124"
  },
  "log_level": "INFO", // Change the minimum log message severity. INFO is recommended, DEBUG if errors occur
  "startup_timeout": 60, // Time that Testrun should wait for a device to obtain an IP address before cancelling
  "monitor_period": 300, // Change the monitor period to the wait time (for Testrun to collect evidence) in seconds
  "max_device_reports": 5 // How many device reports to keep before overwriting
}
```

**Comment by jboddey** [comment]
Hi @chspeck. I am going to close this issue now that it is with the device qualification team. Could you continue communications with them on the issue?
