### ISSUE TITLE
Github - Read.md file missing for modules

### ISSUE THREAD

**Issue by travellingmonk** [google/testrun#315]
Hi,

A m/f has reported about a bug where on visiting [https://github.com/google/testrun/blob/main/docs/test/modules.md](https://github.com/google/testrun/blob/main/docs/test/modules.md&sa=D&source=buganizer&usg=AOvVaw0i4HFlN4feFhYvoxQNx0Cp) , and clicking on either DNS, Nmap, NTP or TLS lead to a '404 - page not found' error. Could you please look into it?

**Comment by jboddey** [comment]
Documentation update has been released into dev. This will be released in v1.2 which is due 29th March.
