### ISSUE TITLE
The MAC address of a usb ethenet device is incorrectly picked up by the single ip connection test

### ISSUE THREAD

**Issue by markt-checkit** [google/testrun#750]
**Description**
The MAC address of usb ethenet interface is incorrectly picked up by the single ip connection test. When running the test you can see the DEBUG info displaying a second MAC address which corresponds with the usb ethernet interface.

**Steps to Reproduce**
1. Use a usb ethernet interface as one of your ethernet interfaces.
2. Start a testrun with reporting set to DEBUG 
3. Look at the result of the single ip test - https://github.com/google/testrun/blob/549641c26a1ec0b6e240deb5772c7268d66728ca/modules/test/conn/python/src/connection_module.py#L226
5. It always shows mutiple mac addresses, one of which is the usb ethernet interface used to connect to the device under test.

**Expected behavior*
The usb ethernet interface's macAddress is ignored.

**Environment:**
 - OS: Ubuntu
 - 24.04 LTS

**Additional context**
 I tried this with 2 different usb ethernet network adapters

**Comment by duncangreene** [comment]
Can confirm I also see same behaviour on Testrun 1.4 as per screenshot below.

![image](https://github.com/user-attachments/assets/40f3a0c8-0fbd-49ce-8fd1-e21f1ff9859b)

**Comment by duncangreene** [comment]
Can confirm this also happens when using onboard Ethernet card, it's not limited to USB Ethernet adapters. I am running in --single-intf mode.

![Screenshot from 2024-09-06 11-56-13](https://github.com/user-attachments/assets/14b65979-09b7-49b4-ac4a-f72a4f259639)

**Comment by jboddey** [comment]
Hi Duncan, have you disabled the ethernet adapters used by Testrun for IPv4 and IPv6 in system settings? If so, I will take a look into this.

**Comment by duncangreene** [comment]
Apologies for the delay in getting back to you on this one! I thought I had sufficiently disabled the network adapter within settings (by virtue of the toggle slider being off).

![image](https://github.com/user-attachments/assets/8e6f2946-f3b7-436f-82a5-bd3aca822c5c)

Having re-read the latest Get Started guide though (and your comment above), I see that you ask to explicitly disable IPv4 and IPv6 in the adapter settings too.

![image](https://github.com/user-attachments/assets/bc959603-deab-46e9-8dbe-6d68c8d2aab7)

Having done this and re-run, I no longer see the adapter MACs being picked up by the single_ip test in v.1.4.

![image](https://github.com/user-attachments/assets/43d46646-4630-49e0-bd62-b0328a64f032)

Might be worth @markt-checkit confirming if they had IPv4 and IPv6 enabled still as I had.

**Comment by jboddey** [comment]
Thanks @duncangreene. We have now added a check for the adapter MAC addresses for the single IP test in the dev branch - so this shouldn't occur after the next release.
