### ISSUE TITLE
DNS Module URLs truncated in HTML and PDF Reports

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#898]
**Describe the bug**
The URLs shown below are truncated in .pdf and .html reports.

![Image](https://github.com/user-attachments/assets/a45d3b4c-deaf-4f82-b4c2-64b1377c6230)

![Image](https://github.com/user-attachments/assets/486675f3-ebad-494f-9aa1-3c98bb085318)

**To Reproduce**
1. View report for a device that conducts DNS queries for (longer) hostnames. Problem is likely amplified if DNS returns AAAA records for IPv6 addresses which take up more screen real estate in the table.

**Expected behavior**
Potentially word wrap the Resolved IP and/or URL columns, or adopt landscape layout for this page.

**Environment (please provide the following information about your setup):**
 - OS: Windows 11 Pro
 - Web Browser: Chrome 129.0.6668.101

**Comment by KrystsinaT** [comment]
@jboddey the issue reported with ID 374258745

**Comment by jboddey** [comment]
This has now been merged into dev and will be released in v2.1

**Comment by duncangreene** [comment]
@jboddey @KrystsinaT just confirming this issue is still present in 2.1.

![Image](https://github.com/user-attachments/assets/c5099b4d-c9d6-495a-aaf9-b53efd92b684)

**Comment by duncangreene** [comment]
I noticed on another report that there is actually supposed to be a 'Count' column displayed too, which isn't visible in the screenshot in the comment above.

![Image](https://github.com/user-attachments/assets/57d78fe6-fec7-4bb0-b6a5-86d23c115517)

**Comment by duncangreene** [comment]
@jboddey @KrystsinaT Should I open a new issue for this or will this one be reopened?

**Comment by duncangreene** [comment]
@jboddey Did you see the above messages that this was still present in v2.1? I haven't been able to check in v2.1.1 due to #1239.

**Comment by KrystsinaT** [comment]
@duncangreene I tried to check with my test device on the version 2.1.1. I see I haven't got the IP resolved info so my results table is not truncated. I suppose if the IP resolved column is filled in the table might be cut. @jboddey could you check please?

![Image](https://github.com/user-attachments/assets/605703e6-aa20-444a-bca8-bc947ba7548f)

**Comment by KrystsinaT** [comment]
@duncangreene thank you for pointing it out. I will report an issue.
