### ISSUE TITLE
"Non-complaint" typo on report

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#900]
**Describe the bug**
"compliant" is spelt complaint in the report below.

![Image](https://github.com/user-attachments/assets/dbe352af-2c15-4c81-aeee-4131499ab4be)

**Expected behavior**
Text to say "compliant".

**Environment (please provide the following information about your setup):**
 - Testrun v2.0

**Comment by jboddey** [comment]
This has been fixed and merged into dev. This will be released in v2.1.
