### ISSUE TITLE
Clarity on results list count in report

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#927]
**What is the problem your feature is trying to solve?**
Where are the numbers derived from for the metric below?

![Image](https://github.com/user-attachments/assets/4b16a152-eaaf-40b3-b012-6ddc53bfcbe7)

In the case of the above screenshot, there were 42 rows in results list table, 2 of which had a result of "Error" (the two TLS server tests).

Another example below.

![Image](https://github.com/user-attachments/assets/3a7c7132-cc4b-4cf4-9920-cf52c96d796f)

In the case of the above screenshot, there were 39 rows in the results list table (the "Protocol" module was unticked).

**Describe the solution you think would solve the problem**

- Is the first number the count of tests that executed without error? As opposed to total number of tests in the table?
- What does the second number represent?

**Comment by KrystsinaT** [comment]
@jboddey we have a similar issue reported on our side . Take a look please 375407324
