### ISSUE TITLE
Excessive MQTT DEBUG messages

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#929]
**Describe the bug**
Unsure if this is a bug per se, but I get the below DEBUG messages from MQTT every 5 seconds during normal use sometimes in Testrun 2.0. Is this expected behaviour? I don't believe this always happens, and can try to get steps to replicate once I track it down (if it is not expected behaviour).

![Image](https://github.com/user-attachments/assets/ea82716d-3719-466d-ac35-2622ca268e10)

**To Reproduce**
1. TBC if behaviour is not expected

**Expected behavior**
The DEBUG messages don't appear to differ very much, and I'm unsure of their value. Should they be TRACE?

**Environment (please provide the following information about your setup):**
 - Testrun 2.0

**Comment by jboddey** [comment]
Hi Duncan, a PR has been created to remove excess MQTT logging at #930 and will be released in v2.1
