### ISSUE TITLE
NMAP Test Results - '"security.services.unknown.XXX' and convoluted results structure

### ISSUE THREAD

**Issue by noursaidi** [google/testrun#94]
Service detection is failing against unknown ports.

I also don't think the structure of the nmap tests are feasible - each nmap test (e.g. security.services.ftp) should be it's own test like the other items, and a final security.services.unknown test as a catchall.

I don't undestand why the nmap tests have a special convoluted structure to the results. 

```
        "security.services.unknown.993": {
          "tcp_ports": {
            "993": {
              "description": "Undefined port",
              "allowed": false,
              "result": "non-compliant"
            }
          }
        },
        "security.services.unknown.995": {
          "tcp_ports": {
            "995": {
              "description": "Undefined port",
              "allowed": false,
              "result": "non-compliant"
            }
          }
        },
        "security.services.unknown.23451": {
          "tcp_ports": {
            "23451": {
              "description": "Undefined port",
              "allowed": false,
              "result": "non-compliant"
            }
          }
```

**Comment by jboddey** [comment]
The nmap module now provides the correct structure. However, we have not yet re implemented reporting of unknown ports. This will be added in the future. Closing.
