### ISSUE TITLE
Testing hangs at Waiting for Device after interface swap

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#978]
**Describe the bug**
After changing the interface to use for the device under test, future tests hang at "Waiting for Device", and error is thrown in logs.

![Image](https://github.com/user-attachments/assets/0305141b-188a-44c7-ae4b-b644eea49b14)

![Image](https://github.com/user-attachments/assets/f7ea3350-28a5-415c-b219-7d7f88a022b6)

**To Reproduce**
1. Have Testrun running perfectly okay with a given (USB Ethernet) network adapter for the device under test.
2. With no testing running, unplug the (USB Ethernet) network adapter, and plug in a different/spare one.
3. Testrun detects that the network adapter configured for the device under test is no longer available and the user is prompted to choose another network adapter.
4. Choose the new network adapter as the connection for the device under test.
5. Attempt to run a test.
6. Observe error as in above screenshot and testing hang at "Waiting for Device".

**Expected behavior**
Error should not be thrown, and testing should work as expected.

**Workaround**
Stop, restart and reconfigure Testrun to use the new network adapter.

**Environment (please provide the following information about your setup):**
 - Ubuntu 24.4.01
 - Testrun 2.0.1
 - Additional hardware (network adapters): [USB Ethernet adapter](https://www.amazon.co.uk/UGREEN-Ethernet-Aluminum-Internet-Compatible-Sliver/dp/B07M91X2NW/ref=sr_1_3?crid=3BJFOGEVPVQWF&dib=eyJ2IjoiMSJ9.8TWCKH4tDqHWaWFuzNGcI1_SYgPEt3weVvHMfcpDV7u3kaCHLJGERyhmfQHpu2Ac9NPiywY0q5WcS2ne3RnKDvPGpSxPsc-DaEATQp-peq69WcnlJcjaj70r3SL9HlSDPfEggCj1Xm_XCsgx-rAe8Yd3Qaq6RBUlNC18b74VOWiQ0zsjFpmTPw3QwbmhbAqO2jiwUmBZqb6MaInXNfe2xV233TGzpYvuPztIOO9xqL0wOmnBRWv_nUiOkSsV4XUHWPCSJJgn7KOLIIGQLAK07nZR4xdRVr2Fry0wWI0pHfo.ZshDloPAThj275o7zPjloUurIMUcbfcldeCJpLDhVNs&dib_tag=se&keywords=ugreen+usb+ethernet&nsdOptOutParam=true&qid=1732033905&s=computers&sprefix=ugreen+usb+ethernet%2Ccomputers%2C61&sr=1-3)

**Comment by jhughesbiot** [comment]
Can you verify the device was properly configured after it is connected?  It maybe detected by the system but not configured properly for Testrun's usage.

**Comment by duncangreene** [comment]
> Can you verify the device was properly configured after it is connected? It maybe detected by the system but not configured properly for Testrun's usage.

I can confirm the 'new' interface was configured in the Settings panel prior to running the test above.

Out of interest I just tried to replicate without configuring the 'new' interface in Settings. Testrun rightly won't allow you to start a test in this case.

![Image](https://github.com/user-attachments/assets/5a1b92f4-7691-408c-8b7a-1c5bb17f130b)

**Comment by jhughesbiot** [comment]
My question regarding configuration was about the OS level.  While I did see you looking at a portion of the configuration in the OS, it was not the full configuration, i.e. dhcp options, etc.  Could you do two things to confirm this issue with an adapter switch vs the adapter configuration itself?

1. Verify both interfaces are configured in an identical manner
2. Connect the errant interface before starting testrun and use it without switching.  

If the issue persists without switching we know it is not the switching mechanism but the interface configuration and/or the adapter itself.

**Comment by duncangreene** [comment]
Both items shown in the video below, which is essentially the vice versa of the video above (swapping from the interface ending :8f to the interface ending :40).

https://github.com/user-attachments/assets/e4dc95b0-8694-4154-b59c-610fba9b80a0

P.S. On a completely separate note you'll see in the above video (00:44 - 01:57) a browser caching issue that I've had a few times. I'm a bit out of touch with cache control mechanisms these days but is there merit in implementing some to prevent this occurring? I can spin off a feature request if so.

**Comment by KrystsinaT** [comment]
@jboddey  The issue was tested in scope of ticket 380232279. Fixed.
