### ISSUE TITLE
API - Ambiguous Add/Edit Actions resulting in unintentionally overwriting a device

### ISSUE THREAD

**Issue by noursaidi** [google/testrun#99]
There is a risk of overwriting an existing device instead of creating a new device, as devices are keyed by mac address and there is no explicit add or edit action in the API.

For example, if there is an existing device with MAC_ADDRESS_1, and a user intends to add a new device, but accidently uses MAC_ADDRESS_1, the existing device will be overwritten with the contents of the new device.

Just raising this, not necessarily expecting an update to this

**Comment by jboddey** [comment]
Closing this. The UI now prevents the MAC address from being modified in the edit device modal.
